config/routes.rb
Rails.application.routes.draw do
  get 'results/show'
  
  root "test#index"
  
  resources :test, only: %i[index]
  resources :questions, except: %i[index edit update destroy]

  scope "/:locale", constraints: { locale: /en|ja/ }do
    resources :answers, only: %i[show]
  end
  
  resources :results, only: %i[show]

  get '/control_session', to: 'cycles#control_session' 
  get '/count_questions', to: 'cycles#count_questions'
  get '/browserback_session', to: 'cycles#browserback_session'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :explanation, presence: true
  validates :explanation, length: { in: 10..100 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question

  validates :choice_text, presence: true
end

app/models/cycle.rb
class Cycle < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
    has_one :answer
    has_many :choices

    validates :content, presence: true
    validates :content, length: { in: 10..100 }
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/answers_controller.rb
require 'wikipedia'

class AnswersController < ApplicationController
  def show
    @answer = Answer.find_by(question_id: params[:id])
    @selected_choice_text = session[:selected_choice_text]
    @select_answer = Choice.find_by(choice_text: @selected_choice_text)
    
    if session[:true_count] && session[:false_count]
      @true_count = session[:true_count]
      @false_count = session[:false_count]
    end
    
    @count = session[:count]
    
    get_wikipedia_information
    
    case I18n.locale
    when :ja
      render "answers/ja/show"
    when :en
      render "answers/en/show"
    end
    
    #if @answer.nil?
    #  flash[:error] = '回答が見つかりませんでした。'
    #  redirect_to root_path # 回答がない場合はrootに飛ぶ
    #end
  end

  #"cyclesコントローラ―のcount_questionアクション内で実行するため不要"
  #def check_answer
  #  data = params[:choice_text]
  #  session[:selected_choice_text] = data

  #  @select_answer = Choice.find_by(choice_text: data)
  #  if @select_answer
  #    redirect_to answer_path(@select_answer.question_id)
  #  else
  #    redirect_to root_path
  #  end

    #以下はデータを受け取れているかを確認した物
    #if @select_answer
    #  if @select_answer.is_correct == true
    #    redirect_to answer_path(@select_answer.question_id)
    #  else
    #    redirect_to question_path(@select_answer.question_id)
    #  end
    #else
    #  redirect_to root_path
    #end
  #end

private

  def get_wikipedia_information

    wiki_data = Wikipedia.find(@select_answer.choice_text)
    @wiki_link = wiki_data.fullurl

    if wiki_data.summary.blank?
      @wiki_info = "Wikipediaに情報がありません"
    else
      @wiki_info = wiki_data.summary[0, 150] + (wiki_data.summary.length > 150 ? "....." : "")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController

    def control_session
        if session[:count]
            session[:count] += 1
        else
            session[:count] = 0
            session[:true_count] = 0
            session[:false_count] = 0
            session[:questions_id] = Question.pluck(:id)
        end

        if session[:count] == 5
            session.delete(:count)
            session.delete(:true_count)
            session.delete(:false_count)
            session.delete(:questions_id)

            redirect_to root_path
        else
            ids = session[:questions_id]
            random_id = ids.sample
            session[:questions_id].delete(random_id)

            redirect_to question_path(random_id)
        end
    end

    def count_questions
        data = params[:choice_text]
        session[:selected_choice_text] = data

        @select_answer = Choice.find_by(choice_text: data)

        if @select_answer.is_correct == true
            session[:true_count] += 1
        else
            session[:false_count] += 1
        end

        redirect_to answer_path(I18n.locale, @select_answer.question_id)
    end

    def browserback_session
        session.delete(:count)
        session.delete(:true_count)
        session.delete(:false_count)
        session.delete(:questions_id)

        redirect_to root_path
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def show
    @question = Question.find(params[:id])
    @choices = Choice.where(question_id: params[:id])
    #@ids = session[:questions_id]

    @count = session[:count] + 1

  end

  def new
    @question = Question.new
  end

  def create
    begin
      ActiveRecord::Base.transaction do
        @question = Question.create!(question_params)
        answer = @question.create_answer(answer_params)
        raise if answer[:explanation].blank?

        choice_create_count = 0
        true_count = 0
        4.times do
          choice = @question.choices.create(choice_params(choice_create_count))
          raise if choice[:choice_text].blank?

          if choice[:is_correct] == true
            true_count += 1
          end
          choice_create_count += 1
        end
        raise if true_count != 1

        flash[:notice] = "送信が完了しました。ご協力ありがとうございます。"
        redirect_to root_path
      end
    rescue
      flash[:alert] = "送信に失敗しました。()内の規定したがって作成してください。"
      redirect_to new_question_path
    end
  end

  private

  def record_not_found
    flash[:error] = "レコードが見つかりませんでした。"
    redirect_to root_path
  end

  def question_params
    params.require(:question).permit(:content)
  end

  def choice_params(index)
    params.require(:question).require(:choices).require(index.to_s).permit(:choice_text,:is_correct)
  end

  def answer_params
    params.require(:question).require(:answer).permit(:explanation)
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def show
    @true_count = session[:true_count]
    @false_count = session[:false_count]
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController

def index
end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/answers/en/show.html.erb
<div class="mx-auto max-w-screen-2xl px-4 md:px-8">
  <div class="flex-container bg-gray-300">
    <div class="flex-col text-center">

      <% if @select_answer.is_correct == true %>

        <div>
          <p class="text-red-500 text-2xl font-bold mt-12">Correct</p>
          <p class="mt-9"><%= @select_answer.choice_text %></p>
          <p class=" text-start px-10 mt-6"><%= @answer.explanation %></p>
          <div class="align-items flex-end">
            <p class=" text-center px-10 mt-6 text-blue-700">-------wikipedia-------</p>
            <p class=" text-start px-10 mt-1"><%= @wiki_info %></p>
            <p class="text-end px-10 mt-1 text-blue-700"><%= link_to "View more", @wiki_link %></p>
         </div>
        </div>

      <% else %>

        <div>
          <p class="text-blue-700 text-2xl font-bold mt-12">Incorrect</p>
          <p class="mt-9"><%= @select_answer.choice_text %></p>
          <p class=" text-start px-10 mt-6"><%= @answer.explanation %></p>
        </div>

      <% end %>

      <div class="flex-cont-end">
        <% if session[:count] != 4%>
            <div class="text-xl">
              <p><%= "Correct #{@true_count} : Incorrect #{@false_count}"%></p>
            </div>

            <div class="mt-3">
              <button class="bg-gray-600 hover:bg-gray-500 text-white px-4 py-2" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2); border-radius: 20px">
                <p><%= link_to "Next", control_session_path %></p>
              </button>
            </div>

        <% else %>
              <button class="bg-gray-600 hover:bg-gray-500 text-white px-4 py-2" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2); border-radius: 20px">
                <p><%= link_to "Announcement of results", results_show_path %></p>
              </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/answers/ja/show.html.erb
<div class="mx-auto max-w-screen-2xl px-4 md:px-8">
  <div class="flex-container bg-gray-300">
    <div class="flex-col text-center">

      <% if @select_answer.is_correct == true %>

        <div>
          <p class="text-red-500 text-2xl font-bold mt-12">大正解</p>
          <p class="mt-9"><%= @select_answer.choice_text %></p>
          <p class=" text-start px-10 mt-6"><%= @answer.explanation %></p>
          <div class="align-items flex-end">
            <p class=" text-center px-10 mt-6 text-blue-700">-------wikipediaの情報-------</p>
            <p class=" text-start px-10 mt-1"><%= @wiki_info %></p>
            <p class="text-end px-10 mt-1 text-blue-700"><%= link_to "続きを見る", @wiki_link %></p>
         </div>
        </div>

      <% else %>

        <div>
          <p class="text-blue-700 text-2xl font-bold mt-12">不正解</p>
          <p class="mt-9"><%= @select_answer.choice_text %></p>
          <p class=" text-start px-10 mt-6"><%= @answer.explanation %></p>
        </div>

      <% end %>

      <div class="flex-cont-end">
        <% if session[:count] != 4%>
            <div class="text-xl">
              <p><%= "正解数#{@true_count} : 不正解数#{@false_count}"%></p>
            </div>

            <div class="mt-3">
              <button class="bg-gray-600 hover:bg-gray-500 text-white px-4 py-2" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2); border-radius: 20px">
                <p><%= link_to "次へ", control_session_path %></p>
              </button>
            </div>

        <% else %>
              <button class="bg-gray-600 hover:bg-gray-500 text-white px-4 py-2" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2); border-radius: 20px">
                <p><%= link_to "結果発表", results_show_path %></p>
              </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    
  </head>

  <body class="bg-auto bg-center bg-no-repeat" style="background-image: url('/assets/soccer-studium-04.png')">
    <script>
      window.history.pushState(null, null, null);
      window.addEventListener('popstate', function(e) {
      // console.log("test")
      if  (confirm('ホームに戻りますが、本当に戻りますか？')) {
          window.location.href = '<%= browserback_session_path %>';
          // console.log("test")
      } else {
        e.preventDefault(); // ブラウザのデフォルトの戻る動作を無効にする
        history.pushState(null, null, location.href); // ブラウザの履歴を元に戻す
          // console.log("test")
          }
      });
    </script>
    <div class="flex justify-center mt-5">
        <%= image_tag("quiz_by_syuare.png", alt: "app" ,width: 150, height: 200)%>
      </div>
    <main class="container mx-auto px-5 flex flex-col">
      <%= yield %>
    </main>

    <% if flash[:error].present? %>
      <div>
        <%= flash[:error] %>
      </div>
    <% end %>

  </body>
</html>

app/views/questions/new.html.erb
<div class="text-center text-xl">
    <!-- <h2 class="mb-4 text-2xl font-bold text-gray-800 md:mb-6 lg:text-3xl">問題作成</h2> -->
        <p>下記のフォームに入力して問題を作成しましょう。</p>
        <p><span class="text-red-600 text-2xl">※</span>管理人の認証後に作成した問題が出題されるようになります。</p>
</div>

    <% flash.each do |key, value| %>
    <div class="flash <%= key %> text-center text-red-600 mt-3">
        <%= value %>
    </div>
    <% end %>
    <div class="flex flex-col items-center px-4 mt-5">
        <div class="mt-5 space-y-2" style="width: 650px;">
            <%= form_with(model: @question, url: questions_path, method: :post) do |form| %>
                <!-- 質問のフォーム -->
                <p class="text-left"><%= form.label :content,  "問題文の入力(10文字以上100文字以内)"%></p>
                <p><%= form.text_area :content, class: " w-full rounded border bg-gray-50 px-3 py-2 text-gray-800 outline-none ring-indigo-300 transition duration-100 focus:ring" %></p>

                <!-- 選択肢のフォーム -->
                <% 4.times do |i| %>
                    <%= form.fields_for "choices[#{i}]", Choice.new do |choice_form| %>
                    <p><%= choice_form.label :choice_text, "選択肢#{i + 1}の入力(正解の選択肢にはチェックをつけて下さい)"%></p>
                    <div>
                        <%= choice_form.text_field :choice_text, class: " rounded border bg-gray-50 px-3 py-2 text-gray-800 outline-none ring-indigo-300 transition duration-100 focus:ring" %>
                        <%= choice_form.check_box :is_correct %>
                    </div>
                    <% end %>
                <% end %>

                <!-- 回答のフォーム -->
                <%= form.fields_for :answer do |answer_form| %>
                    <p><%= answer_form.label :answer, "解答の入力(10文字以上100文字以内)"%></p>
                    <p><%= answer_form.text_area :explanation, class: " w-full rounded border bg-gray-50 px-3 py-2 text-gray-800 outline-none ring-indigo-300 transition duration-100 focus:ring" %></p>
                <% end %>

            <div class="text-center mt-3">
                <%= form.submit "送信", class: "bg-blue-500 hover:bg-blue-400 text-white px-4 py-2", style: "box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2); border-radius: 10px" %>
            </div>
            <% end %>
        </div>
    </div>

app/views/questions/show.html.erb
<div class="mx-auto max-w-screen-2xl px-4 md:px-8">
    <div class="flex-container bg-gray-300">
        <div class="mx-auto">
            <p class="text-2xl mt-12 text-center"><%= "第#{@count}問"%></p>
            <h2 class=" text-orange-700 text-center mt-6"><%= @question.content %></h2>

            <div class="flex flex-col mt-20 px-12 space-y-4">
                <% @choices.each do |choice| %>
                        <button class="bg-blue-400 hover:bg-blue-300 text-white rounded px-4 py-2" style="box-shadow: 0 3px 6px rgba(0, 0, 0, 0.2);">
                            <a href="<%=count_questions_path(choice_text: choice.choice_text)%>">
                                <form action="/answers_controller/check_answer" method="post">
                                    <%= choice.choice_text %>
                                </form>
                            </a>
                        </button>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/results/show.html.erb
<div class="mx-auto max-w-screen-2xl px-4 md:px-8">
  <div class="flex-container bg-gray-300">
    <div class="flex-col text-center">

      <h2 class=" text-3xl font-bold mt-8">結果発表</h2>
      <% if @true_count == 0 %>
        <div>
          <p class="mt-16">あなたは</p>
          <p><span class="text-red-500 text-2xl">赤ちゃん</span> レベル</p>
          <p  class="mt-7"><%= "あなたは5問中#{@true_count}問正解です。"%></p>
          <p class="text-blue-900 text-2xl mt-1"><%= "次は全問正解目指して頑張りましょう!"%></p>
        </div>

      <% elsif @true_count == 1 %>
        <div>
          <p class="mt-16">あなたは</p>
          <p><span class="text-red-500 text-2xl">少年サッカー選手</span> レベル</p>
          <p  class="mt-7"><%= "あなたは5問中#{@true_count}問正解です。"%></p>
          <p class="text-blue-900 text-2xl mt-1"><%= "次は全問正解目指して頑張りましょう!"%></p>
        </div>

      <% elsif @true_count == 2 %>
        <div>
          <p class="mt-16">あなたは</p>
          <p><span class="text-red-500 text-2xl">社会人サッカー選手</span> レベル</p>
          <p  class="mt-7"><%= "あなたは5問中#{@true_count}問正解です。"%></p>
          <p class="text-blue-900 text-2xl mt-1"><%= "次は全問正解目指して頑張りましょう!"%></p>
        </div>

      <% elsif @true_count == 3 %>
        <div>
          <p class="mt-16">あなたは</p>
          <p><span class="text-red-500 text-2xl">Jリーグ選手</span> レベル</p>
          <p  class="mt-7"><%= "あなたは5問中#{@true_count}問正解です。"%></p>
          <p class="text-blue-900 text-2xl mt-1"><%= "次は全問正解目指して頑張りましょう!"%></p>
        </div>

      <% elsif @true_count == 4 %>
        <div>
          <p class="mt-16">あなたは</p>
          <p><span class="text-red-500 text-2xl">五大リーグ選手</span> レベル</p>
          <p  class="mt-7"><%= "あなたは5問中#{@true_count}問正解です。"%></p>
          <p class="text-blue-900 text-2xl mt-1"><%= "次は全問正解目指して頑張りましょう!"%></p>
        </div>

      <% elsif @true_count == 5 %>
        <div>
          <p class="mt-16">あなたは</p>
          <p><span class="text-red-500 text-2xl">神の子メッシ</span> レベル</p>
          <p  class="mt-7"><%= "あなたは5問中#{@true_count}問正解です。"%></p>
          <p class="text-yellow-600 text-2xl mt-1"><%= "全問正解おめでとうございます！"%></p>
        </div>

      <% end %>
      <div class="flex-cont-end">
        <button class="bg-gray-600 hover:bg-gray-500 text-white rounded px-4 py-2" style="box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);">
          <p><%= link_to "HOME", control_session_path %></p>
        </button>
      </div>